version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: matteo-bropat-eufy-security-ws_server_1
      APP_PORT: 3000

  server:
    image: bropat/eufy-security-ws:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Add any required environment variables here
    volumes:
      # Uncomment and configure if persistent storage is needed
