version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: matteo-eufy-security-ws_server_1
      APP_PORT: 3000

  server:
    image: bropat/eufy-security-ws:latest
    ports:
      - "3993:3000/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/eufy-security-ws:/data"
    restart: unless-stopped